# More info on playground configuration can be found here:
# https://llama-stack.readthedocs.io/en/latest/playground

FROM python:3.12-slim

ARG IMAGE_TAG
WORKDIR /app
COPY . /app/

# Make sure IMAGE_TAG is set
RUN if [ -z "$IMAGE_TAG" ]; then echo "IMAGE_TAG is not set"; exit 1; fi

# Install uv
RUN pip install uv

# Install dependencies using uv
RUN if [ -f "uv.lock" ]; then \
        echo "Lockfile found, using frozen sync"; \
        uv sync --frozen; \
    else \
        echo "Lockfile not found, creating new one"; \
        uv sync; \
    fi

EXPOSE 8501

ENTRYPOINT ["uv", "run", "streamlit", "run", "/app/llama_stack_ui/distribution/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
